### ISSUE TITLE
Can't see the player

### ISSUE THREAD

**Issue by michaelsammler** [JonSn0w/PlayMusic#10]
I have google play music desktop player, I have api checked. I have two other rainmeters working (translucent task bar and Space Hud). 
The album image from the song I am  playing shows up in the downloadfile folder under documents. 
But nothing shows up on my desktop. I tried all the settings in rainmeter. Like coordinates, position, transparency.  
Sorry, just not sure what I am missing for this to show up. Any ideas would be appreciated. The images on Deviant art look great. 
Thanks.

**Comment by tterb** [comment]
A few users had similar issues with the *.rmskin* installer file from v1.2.0, so I would first recommend first downloading the *.rmskin* for the most recent release, [here](https://github.com/JonSn0w/PlayMusic/releases/latest).  
Though, if the problem persists, let me know and I will provide further troubleshooting options.

**Comment by michaelsammler** [comment]
Sorry.  That did not work. I think it might be I have the Desktop player in the wrong place?

**Comment by tterb** [comment]
Okay, to help resolve the issue I've just got a few questions:
  * What version of Rainmeter are you currently using?
  * Which variants(round/square/landscape) are you having this issue with?
  * Have you confirmed that the skin is loaded within Rainmeter?
    - You can check by right-clicking on the Rainmeter logo in your taskbar, as shown in the screenshot below.
<p align="center">
<img src="https://cloud.githubusercontent.com/assets/16360374/23503024/c91560fe-feee-11e6-9dea-8e3dab846722.png" width="360">
</p>

**Comment by michaelsammler** [comment]
Thanks Snow
1.
4.0.0 r2746 64-bit (Jan  1 2017)
Windows 10 Home 64-bit (build 14393)
Path: C:\Program Files\Rainmeter\
IniFile: C:\Users\Michael\AppData\Roaming\Rainmeter\Rainmeter.ini
SkinPath: C:\Users\Michael\Documents\Rainmeter\Skins\

2. I tried all three and non of them show up. But the album art is in the rainmeter file. 
3. Yes, play music shows up in rain meter like in your posted image. 

![screenshot 2017-03-03 17 41 05](https://cloud.githubusercontent.com/assets/10263082/23544068/a64eb7b4-0038-11e7-9ddf-071cca21c46f.png)

![screenshot 2017-03-03 17 37 49](https://cloud.githubusercontent.com/assets/10263082/23543996/41e74c46-0038-11e7-9872-7dcae0a21a3e.png)

**Comment by tterb** [comment]
* Since you're on v4.0 this shouldn't be an issue.
  * This means the scripts of the skin are working somewhere.
  * If you click on the "Load" button in the last screenshot does anything show up?
    * If not, can you confirm that the values shown in the Coordinates field are within the bounds of your desktop?  

If the problem persists, another possible solution may be to re-download the *.rmskin* installer and use it to replace your current installation of the skin.

**Comment by michaelsammler** [comment]
I have clicked that darn load button so many times :-)

The coordinates field are usually 0. I tried adding the coordinates of the corner objects you see in the screenshots (space hub, rainmeter) and still nothing. Like 700 and 0, or o and 500. But nothing. 

When I hit load in the Manage rainmeter window and load settings from the config folder, the settings does open front and center. 

Is it that my files are not in the right places? Not sure where everything is cause I am lazy, but I can find them and move stuff to where it should be. Like I think GPM is still in the download folder, not programs....Could this be  it?

**Comment by tterb** [comment]
That's strange that the settings menu is acting normally when none of the other skins are. My only thought is that maybe the primary skin files were messed up somehow during the install processes.
 
I don't think that the location of GPM should affect the skin since you've shown that the album artwork is already showing up on the PlayMusic folder. 

I'd recommend using the *.rmskin* file [here](https://github.com/JonSn0w/PlayMusic/releases/tag/v1.2.1) to re-install the skin, and then if the problem persists we can troubleshoot further from there.

**Comment by michaelsammler** [comment]
No idea what happened. My GPU reading in rainmeter went crazy. Redownloaded and loaded Space Hud and Play music showed up. So excited. 
It is a bit small on a 1440p monitor. Was not expecting that. 
Thank you for your work and assistance. I am super happy with it. 
![screenshot 2017-03-08 16 51 49](https://cloud.githubusercontent.com/assets/10263082/23694945/11e0bc26-0420-11e7-917a-e0530fe9013d.png)

**Comment by tterb** [comment]
No problem, I'm glad you got everything figured out!
I've also been working to enable scalable sizing for each of the variants in a future release, though the addition of this functionality is more complicated than usual due to the integrated visualizer.
Make sure to let me know if you run into any issues in the future.
